name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      env:
        GOPATH: /home/runner/work/go-mindustry/go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: |
        pwd
        echo $GOPATH
        echo $GOROOT
        ls $GOROOT
        export PATH=$PATH:/home/runner/work/go-mindustry/go/bin
        for i in pkg/*; do golint $i/; done

    - name: Build
      run: go build -v .
